In [2]:
import numpy as np

In [3]:
array2D_1 = np.array([[1, 2, 3], [4, 5, 6]])
array2D_2 = np.array([[10, 20, 30], [40, 50, 60]])

In [4]:
addition_2D = np.add(array2D_1, array2D_2)
print(addition_2D)

[[11 22 33]
 [44 55 66]]


In [5]:
subtraction_2D = np.subtract(array2D_1, array2D_2)
print(subtraction_2D)

[[ -9 -18 -27]
 [-36 -45 -54]]


In [6]:
multiplication_2D = np.multiply(array2D_1, array2D_2)
print(multiplication_2D)

[[ 10  40  90]
 [160 250 360]]


In [11]:
exponentiation_2D = np.power(array2D_1, 2)
print(exponentiation_2D)


[[ 1  4  9]
 [16 25 36]]


In [12]:
modulus_2D = np.mod(array2D_2, array2D_1)
print(modulus_2D)

[[0 0 0]
 [0 0 0]]


In [13]:
scalar_addition_2D = array2D_1 + 5
print(scalar_addition_2D)

[[ 6  7  8]
 [ 9 10 11]]


In [14]:
scalar_multiplication_2D = array2D_1 * 3
print(scalar_multiplication_2D)

[[ 3  6  9]
 [12 15 18]]


In [15]:
array3D_1 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
array3D_2 = np.array([[[10, 20], [30, 40]], [[50, 60], [70, 80]]])

In [16]:
addition_3D = np.add(array3D_1, array3D_2)
print(addition_3D)


[[[11 22]
  [33 44]]

 [[55 66]
  [77 88]]]


In [17]:
subtraction_3D = np.subtract(array3D_1, array3D_2)
print(subtraction_3D)

[[[ -9 -18]
  [-27 -36]]

 [[-45 -54]
  [-63 -72]]]


In [18]:
multiplication_3D = np.multiply(array3D_1, array3D_2)
print(multiplication_3D)

[[[ 10  40]
  [ 90 160]]

 [[250 360]
  [490 640]]]


In [19]:
division_3D = np.divide(array3D_1, array3D_2)
print(division_3D)


[[[0.1 0.1]
  [0.1 0.1]]

 [[0.1 0.1]
  [0.1 0.1]]]


In [20]:
exponentiation_3D = np.power(array3D_1, 2)
print(exponentiation_3D)

[[[ 1  4]
  [ 9 16]]

 [[25 36]
  [49 64]]]


In [21]:
modulus_3D = np.mod(array3D_2, array3D_1)
print(modulus_3D)

[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]


In [22]:
scalar_addition_3D = array3D_1 + 5
print(scalar_addition_3D)

[[[ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]]]


In [23]:
scalar_multiplication_3D = array3D_1 * 3
print(scalar_multiplication_3D)

[[[ 3  6]
  [ 9 12]]

 [[15 18]
  [21 24]]]
