In [1]:
import numpy as np

data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

file_path = 'created_sample.csv'

np.savetxt(file_path, data, delimiter=',')

print("CSV file created and saved as 'created_sample.csv'")


CSV file created and saved as 'created_sample.csv'


In [2]:
loaded_data = np.loadtxt(file_path, delimiter=',')
print("\nData read from CSV file:\n", loaded_data)

scalar_addition = loaded_data + 10
print("\nData after adding 10:\n", scalar_addition)

scalar_multiplication = loaded_data * 2
print("\nData after multiplying by 2:\n", scalar_multiplication)

array_addition = np.add(loaded_data, loaded_data)
print("\nElement-wise addition:\n", array_addition)


Data read from CSV file:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

Data after adding 10:
 [[11. 12. 13.]
 [14. 15. 16.]
 [17. 18. 19.]]

Data after multiplying by 2:
 [[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

Element-wise addition:
 [[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
